### ISSUE TITLE
[BUG] Unable to craft steel ingots via Assembly's fluid bath

### ISSUE THREAD

**Issue by SparkySnips** [itsdinkd/AQM3#103]
**Modpack Version**
1.0.4b
**Minecraft Version**
1.18.2
**Describe the bug**
Inability to craft Assembly's steel ingot via fluid bath

**To Reproduce**
Attempt the Assembly fluid bath recipe for steel ingots. (1 ground iron, 1 ground coal/charcoal, bucket of lava, stirred with pure iron stirring stick)

**Expected behavior**
The default recipe for a steel ingot to function as described in the guide book of Assembly.

**Screenshots**
If applicable, add screenshots to help ex
[latest.log](https://github.com/itsdinkd/AQM3/files/8924730/latest.log)
plain your problem.

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**
Ground iron from Assembly does not even show up within JEI as an item, yet it can be crafted via the manual grinder.

**Comment by itsdinkd** [comment]
Should be fixed in latest version

**Comment by shel2015** [comment]
Aqm3 1.0.6
Minecraft  1.18.2
Assembly line machines 1.18.2-1.4.4.1
This is the latest version of the pack and it still does not work. How can you tell if your modpack is beta. I don't see as beta. If we're I'd stick to the stable version and avoid the beta and all it's problems.
